baseurl = "https://forsblom.netlify.app/"
title = "Elias Forsblom"
theme = "hugo-coder-portfolio"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "eliasforsblom" # Enable or disable Disqus.

[params] # theme parameters
    author = "Elias Forsblom" # Author's name.
    info = "Statistics and data analysis student" # Author's job title or info.
    description = "Elias Forsblom's academic blog" # Site description.
    keywords = "blog,developer,personal, data analysis, statistics, data, analysis" # Site keywords.
    avatarurl = "/images/elias.jpg" 

    footercontent = "Enter a text here."
    fixedbarContent = "Do you want to know me more private?→" 
    fixedbarContentAfter = "Thank You! Please share it if you like it→" 

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/eliasforsblom"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/elias-forsblom-425278191/"
    
# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
    [[menu.main]]
    name = "Contact"
    weight = 3
    url = "contact"
    
ignoredFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]